name: brian.howe
description: uniform
version: 0.0.1
author: xbt595mb.p3nvzn3x@rsheteoy.com
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines:
  pipelines/Makeda_KubAbel_N__WillanMirella_Cassin:
    name: Makeda_KubAbel_N__WillanMirella_Cassin
    description: null
    author: xbt595mb.p3nvzn3x@rsheteoy.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2025-12-05 23:14:53'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/Manuel_StokesAnna_PrenticeClementina_Yost:
    name: Manuel_StokesAnna_PrenticeClementina_Yost
    description: null
    author: xbt595mb.p3nvzn3x@rsheteoy.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2025-12-05 23:14:54'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-12-05 23:14:53'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: xbt595mb.p3nvzn3x@rsheteoy.com
  createdAt: '2025-12-05 23:14:53'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
